import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:on_device_ai/data/model_catalog.dart';
import 'package:on_device_ai/domain/input_image.dart';
import 'package:on_device_ai/domain/model_spec.dart';

/// Access to the ground-truth fixture generated by `tool/reference_predict.py`.
///
/// These tests run on the host VM, not on a device, so assets are read straight
/// off disk relative to the package root (which is `flutter test`'s cwd).
class ReferenceFixture {
  ReferenceFixture(this.json);

  static ReferenceFixture load() {
    final file = File('test/fixtures/reference_predictions.json');
    if (!file.existsSync()) {
      throw StateError(
        'Missing ${file.path}. Run: python3 tool/reference_predict.py',
      );
    }
    return ReferenceFixture(
      jsonDecode(file.readAsStringSync()) as Map<String, dynamic>,
    );
  }

  final Map<String, dynamic> json;

  Map<String, dynamic> get preprocessProbe =>
      json['preprocess_probe'] as Map<String, dynamic>;

  Map<String, dynamic> get normalizationProbe =>
      json['normalization_probe'] as Map<String, dynamic>;

  Map<String, dynamic> probeFor(String modelId) =>
      preprocessProbe[modelId] as Map<String, dynamic>;

  List<int> get sampleIndices =>
      (preprocessProbe['sample_indices'] as List).cast<int>();

  /// Reference top-5 for [imageName] under [modelId].
  List<Map<String, dynamic>> predictionsFor(String imageName, String modelId) {
    final images = json['predictions'] as Map<String, dynamic>;
    final image = images[imageName] as Map<String, dynamic>;
    final model = image[modelId] as Map<String, dynamic>;
    return (model['top5'] as List).cast<Map<String, dynamic>>();
  }
}

Uint8List readRepoFile(String path) {
  final file = File(path);
  if (!file.existsSync()) {
    throw StateError('Missing $path');
  }
  return file.readAsBytesSync();
}

/// The 1001-line ImageNet label file, read from disk.
List<String> readLabels() {
  final raw = File('assets/models/imagenet_labels_1001.txt').readAsStringSync();
  final lines = raw.split('\n');
  while (lines.isNotEmpty && lines.last.trim().isEmpty) {
    lines.removeLast();
  }
  return lines;
}

/// Convenience for tests that need an [InputImage] from a repo asset.
InputImage inputImageFor(String name) => InputImage(
      bytes: readRepoFile('assets/images/$name'),
      source: 'assets/images/$name',
    );

/// The float model's spec, re-exported so resize tests need not import the
/// catalogue directly.
ModelSpec specForFloatModel() => ModelCatalog.mobileNetV2Float32;
